lr_finder:
  enable: False

model:
  name: 'mobilenetv3_large'
  classification: True
  pretrained: False
  save_chkpt: False
  feature_dim: 1280
  dropout_cls:
    p: 0.2
    dist: 'bernoulli'

loss:
  name: 'am_softmax'
  softmax:
    s: 1.0
    compute_s: False

sampler:
  train_sampler: 'RandomSampler'

metric_losses:
  enable: False

train:
  optim: 'sam'
  lr: 0.016
  nbd: True
  max_epoch: 200
  weight_decay: 5e-4
  batch_size: 84
  lr_scheduler: 'warmup'
  warmup: 5
  base_scheduler: 'reduce_on_plateau'
  early_stoping: True
  train_patience: 5
  lr_decay_factor: 200
  deterministic: True
  patience: 5
  gamma: 0.1

sam:
  enable: True
  rho: 0.05

test:
  batch_size: 128
  evaluate: False
  eval_freq: 1
